name: ml-laboratory
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - flake8
  - coverage
  - sip
  - six
  - click
  - sphinx
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - statsmodels
  - plotly
  - pillow
  - nb_conda_kernels
  - nb_conda
  - jupyter
  - jupyterlab
  - widgetsnbextension
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - ipywidgets
  - tensorflow
  - keras
  - ruamel_yaml
  - h5py
  - xgboost
  - catboost
  - shap
  - mypy
  - pyarrow
  - pip:
    - python-dotenv
    - opencv-python
