name: ml-laboratory
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - flake8
  - coverage
  - sip
  - six
  - click
  - sphinx
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - plotly
  - pillow
  - jupyter
  - nb_conda_kernels
  - nb_conda
  - tensorflow
  - keras
  - ruamel.yaml
  - pip:
    - awscli
    - python-dotenv
