repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
        exclude: "not_rendered.yml|invalid-config.yaml"
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
      - id: flake8
        exclude: models
        additional_dependencies:
          [
            flake8-bandit,
            flake8-bugbear,
            flake8-builtins,
            flake8-comprehensions,
            flake8-debugger,
            flake8-eradicate,
            flake8-implicit-str-concat,
            flake8-logging-format,
            flake8-mutable,
            flake8-pytest-style,
            flake8-print,
            flake8-use-pathlib,
            pep8-naming
          ]