[tool.poetry]
name = "ml-lab"
version = "0.0.1"
description = "Machine Learning lab code & examples"
authors = ["Jean Metz"]

[tool.poetry.dependencies]
python = "3.9.2"
jupyterlab = { version = "^3.0.16", optional = true }
ipywidgets = { version = "^7.6.3", optional = true }
ipykernel = { version = "^5.5.5", optional = true }
environs = "^9.3.2"
click = "^8.0.1"
pandas = "^1.2.4"
numpy = "^1.20.3"
python-dotenv = "^0.17.1"
matplotlib = "^3.4.2"
seaborn = "^0.11.1"
scipy = "^1.6.3"
Pillow = "^8.2.0"
scikit-learn = "^0.24.2"
scikit-image = "^0.18.1"
statsmodels = "^0.12.2"


[tool.poetry.dev-dependencies]
black = "^21.5b2"
flake9 = "^3.8.3"
mypy = "^0.812"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-sugar = "^0.9.4"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.4.3"
flake8-use-pathlib = "^0.2.0"
flake8-noqa = "^1.1.0"
flake8-assert-msg = "^1.1.1"
flake8-typing-imports = "^1.10.1"
responses = "^0.13.3"
ipdb = "^0.13.9"
pip-licenses = "^3.4.0"
pre-commit = "^2.13.0"
isort = "^5.8.0"


[tool.poetry.extras]
jupyter = ["ipykernel", "jupyterlab", "ipywidgets"]


[tool.flake8]
max-line-length = 120
max-complexity = 10
ignore = ["W504", "W503", "E231", "E203"]
exit-zero = 1

[tool.pytest.ini_options]
addopts = "--pdbcls=IPython.terminal.debugger:TerminalPdb --cov=src --cov-fail-under 80"


[tool.coverage.report]
omit = ["*/__init__.py", ".mypy_cache", ".reports", ".git"]
show_missing = true

[tool.coverage.run]
omit = ["*/__init__.py", ".mypy_cache", ".reports", ".git"]

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '(\.git|\.mypy_cache|\.venv)'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

